/* LoyaltyOS Service Worker v11 — réseau, cache et push */
const CACHE_NAME='loyaltyos-v11-2026-08-03';
const STATIC_ASSETS=['/','/index.html','/client.html','/merchant.html','/admin.html','/manifest.json','/favicon-96x96.png','/apple-touch-icon.png','/web-app-manifest-192x192.png','/web-app-manifest-512x512.png','/html5-qrcode.min.js'];
const HTML_PATHS=['/','/index.html','/client.html','/merchant.html','/admin.html'];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE_NAME).then(c=>Promise.allSettled(STATIC_ASSETS.map(u=>c.add(u).catch(()=>{})))).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))).then(async()=>{await self.clients.claim();const cs=await self.clients.matchAll({includeUncontrolled:true});cs.forEach(c=>c.postMessage({type:'SW_UPDATED',version:CACHE_NAME}));})));
async function networkFirst(req,fallback='/index.html'){const c=await caches.open(CACHE_NAME);try{const r=await fetch(req,{cache:'no-store'});if(r?.ok)c.put(req,r.clone()).catch(()=>{});return r;}catch(e){return(await c.match(req))||c.match(fallback);}}
async function staleWhileRevalidate(req){const c=await caches.open(CACHE_NAME),cached=await c.match(req);const fresh=fetch(req).then(r=>{if(r?.ok&&r.type!=='opaque')c.put(req,r.clone()).catch(()=>{});return r;}).catch(()=>null);return cached||fresh;}
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.hostname.includes('supabase.')){e.respondWith(fetch(e.request));return;}if(e.request.mode==='navigate'||HTML_PATHS.includes(u.pathname)){e.respondWith(networkFirst(e.request));return;}e.respondWith(staleWhileRevalidate(e.request));});
self.addEventListener('push',e=>{let d={title:'LoyaltyOS',body:'Nouveau message',url:'/client.html?open=notifs'};try{if(e.data)d={...d,...e.data.json()};}catch(_){if(e.data)d.body=e.data.text();}const o={body:d.body,icon:d.icon||'/web-app-manifest-192x192.png',badge:d.badge||'/favicon-96x96.png',data:{...(d.data||{}),url:d.url||d.data?.url||'/client.html?open=notifs',merchant_id:d.merchant_id||d.data?.merchant_id||null},tag:d.tag||`loyaltyos-${d.merchant_id||'general'}`,renotify:true,vibrate:[100,50,100],actions:[{action:'open',title:'Voir ma carte'},{action:'dismiss',title:'Ignorer'}]};e.waitUntil(self.registration.showNotification(d.title,o));});
self.addEventListener('notificationclick',e=>{e.notification.close();if(e.action==='dismiss')return;const target=new URL(e.notification.data?.url||'/client.html?open=notifs',self.location.origin);e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(async list=>{for(const c of list){const cu=new URL(c.url);if(cu.pathname===target.pathname){if('navigate'in c)await c.navigate(target.href);return c.focus();}}return clients.openWindow?clients.openWindow(target.href):undefined;}));});
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting();});
